### ISSUE TITLE
Animation doesn't work

### ISSUE THREAD

**Issue by VitalyName** [dbfannin/ngx-growl#1]
Hello. When I update from **ng2-growl** to **ngx-growl**, the animation stops working. The growl window appears at the destination, and disappears later.
Angular: 4,
Browsers: Chrome, Firefox.

**Comment by VitalyName** [comment]
I added an example in which you can see the difference between ng2-growl and ngx-growl
[https://github.com/VitalyName/ngx-growl-animation-error](url)

**Comment by VitalyName** [comment]
I found it and add pull request. Please update your package in npm repository.
[https://github.com/dbfannin/ngx-growl/pull/2]()

**Comment by dbfannin** [comment]
Your PR should have resolved the issue. Thanks!

**Comment by VitalyName** [comment]
When to expect an update in the npm repository?

**Comment by dbfannin** [comment]
It's already been published. 1.0.2

**Comment by VitalyName** [comment]
I did not fix everything, there is one more place in the code that allows the closing animation to work correctly. So I fix it and create pull request. Please add it fix in NPM repository also.
[pull request](https://github.com/dbfannin/ngx-growl/pull/3)
